name: Coding-style
on:
  push:
    branches:
      - main

jobs:
  check-coding-style:
    runs-on: ubuntu-latest

    env:
      REPORTS_DIR: "/tmp"
      EXPORT_FILE: "/tmp/coding-style-reports.log"

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Pull the coding-style docker
        run: |
          docker pull ghcr.io/epitech/coding-style-checker:latest && 
          sudo docker image prune -f

      - name: Run the coding-style docker
        run: >
          docker run --rm -i
          -v "$GITHUB_WORKSPACE":"/mnt/delivery"
          -v "$REPORTS_DIR":"/mnt/reports"
          ghcr.io/epitech/coding-style-checker:latest
          "/mnt/delivery" "/mnt/reports"

      - name: Check for the errors
        run: >
          if [[ "$(cat $EXPORT_FILE)" == "" ]]; then
            echo "SUCCESS";
          else 
            echo "::error:: $(cat $EXPORT_FILE)";
          fi
